### ISSUE TITLE
jinja2 tempalte ACL update error

### ISSUE THREAD

**Issue by jmurriste** [ansible-collections/arista.eos#124]
##### SUMMARY
Using a jinja template with ansible to push ACL configurations, on the first instance without ACL configured at the router, the PB is working fine. ACL is configured, when try to push to add a new network to the ACL there is an error.

##### ISSUE TYPE
- Bug Report or problem

##### COMPONENT NAME

arista.eos.eos_config module/plugin

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jorge/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

##### CONFIGURATION
```paste below
none
```

##### OS / ENVIRONMENT
 vEOS
Hardware version:      
Serial number:         
Hardware MAC address:  5000.00af.9e14
System MAC address:    5000.00af.9e14

Software image version: 4.24.2.1F
Architecture:           i686
Internal build version: 4.24.2.1F-18613460.42421F
Internal build ID:      23603173-65f1-4b36-b93b-0aaae751df19

Uptime:                 1 weeks, 0 days, 5 hours and 10 minutes
Total memory:           2014428 kB
Free memory:            978372 kB

last ansible module arista.eapi

##### STEPS TO REPRODUCE
the playbook runs fine on the first time.
but on the second time: error due a permit invalid

```yaml
---
- name: Run commands on remote LAB devices
  hosts: eos_switches
  gather_facts: false

  tasks:

    - name: run show version on remote devices
      eos_command:
        commands: "show version"
      register: eos_version

    - name: 'Show running version'
      debug:
        var: eos_version

    - name: render a Jinja2 template onto an Arista switch
      arista.eos.eos_config:
        backup: yes
        src: /home/jorge/arista/playbooks/eapi/acl_jinja2.j2
```

cl_jinja2.j2
ip access-list standard 3001
{% for acl_entry in acl_entries -%}
    permit {{ acl_entry.value }}
{% endfor %}

acl_vars_j2.json
{
  "acl_entries": [
    {
      "value": "10.10.10.0/24"
    },
    {
      "value": "10.10.11.0/24"
    },
    {
      "value": "10.10.12.0/24"
    },
    {
      "value": "10.10.13.0/24"
    }
  ]
}

##### EXPECTED RESULTS
I would like to CRUD and ACL using Jinja2 template only pasing a Json DIC:

ansible-playbook -i inventory acl_template.yaml --extra-vars "@one_entry_acl_vars_j2.json" -vvvv  

##### ACTUAL RESULTS
firs time, is OK
Standard IP Access List 3001
        10 permit 10.10.15.0/24
Second time: error:
 Invalid input (at token 0: 'permit')\n",
         

```paste below
TASK [render a Jinja2 template onto an Arista switch] ***************************************************************************************************************************************************************************************
task path: /home/jorge/arista/playbooks/eapi/acl_template.yaml:17
<10.253.36.40> attempting to start connection
<10.253.36.40> using connection plugin httpapi
<10.253.36.40> found existing local domain socket, using it!
<10.253.36.40> updating play_context for connection
<10.253.36.40>
<10.253.36.40> local domain socket path is /home/jorge/.ansible/pc/fad62c5994
<10.253.36.40> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.36.40> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710 `" && echo ansible-tmp-1602532003.32-131673504149710="` echo /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710 `" ) && sleep 0'
Using module file /home/jorge/.ansible/collections/ansible_collections/arista/eos/plugins/modules/eos_config.py
<10.253.36.40> PUT /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/tmp0KqxW5 TO /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py
<10.253.36.40> EXEC /bin/sh -c 'chmod u+x /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/ /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py && sleep 0'
<10.253.36.40> EXEC /bin/sh -c '/usr/bin/python3 /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py && sleep 0'
<10.253.36.40> EXEC /bin/sh -c 'rm -f -r /home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py", line 102, in <module>
    _ansiballz_main()
  File "/home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_config.py", line 575, in <module>
  File "/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_config.py", line 474, in main
  File "/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py", line 724, in load_config
  File "/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py", line 605, in load_config
  File "/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py", line 642, in edit_config
  File "/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Invalid input (at token 0: 'permit')
fatal: [10.253.36.40]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jorge/.ansible/tmp/ansible-local-3452dKkrx9/ansible-tmp-1602532003.32-131673504149710/AnsiballZ_eos_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_config.py\", line 575, in <module>\n  File \"/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_config.py\", line 474, in main\n  File \"/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py\", line 724, in load_config\n  File \"/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py\", line 605, in load_config\n  File \"/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py\", line 642, in edit_config\n  File \"/tmp/ansible_arista.eos.eos_config_payload_eslowby1/ansible_arista.eos.eos_config_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid input (at token 0: 'permit')\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by GomathiselviS** [comment]
Hi @jmurriste ,

Thanks for submitting the issue. I shall look into this. Meanwhile, we would like you to use the eos_acls resource module, to handle acl configuration on an eos device. Please refer to [eos acls documentaion](https://docs.ansible.com/ansible/2.10/collections/arista/eos/eos_acls_module.html). Feedback on the same will be much appreciated.

**Comment by GomathiselviS** [comment]
@jmurriste  : Please use the `diff_ignore_lines` key to avoid this issue. 

```
 - name: render a Jinja2 template onto an Arista switch
      arista.eos.eos_config:
        backup: yes
        src: acl_jinja2.j2
        diff_ignore_lines: "ip access-list .*"
```

I shall close this issue as the module works as expected. Please let me know if you feel otherwise.
