### ISSUE TITLE
eos_facts acl_interfaces traceback due to an ACL applied to filter a monitor session

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#150]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

eos_facts

##### ANSIBLE VERSION

```paste below
2.10.5
```

##### CONFIGURATION

```paste below
<empty>
```

##### OS / ENVIRONMENT

Arista EOS 4.22.6M, 4.23.5M, & 4.24.3M

##### STEPS TO REPRODUCE

It looks like any device that has an ACL applied to a monitor session (IE a filter that identifies what traffic to mirror when being sent to a packet capture) the acl_intefaces function of the facts module fails.  The below is a valid config and should be parsed correctly.  Other OS platforms could have the same issue like ios.
```bash
ip access-list troubleshooting
  <acl omitted>
!
monitor session FWL source Ethernet43  ip access-group troubleshooting
monitor session FWL destination Ethernet5
```

```yaml
    - name: eos facts
      arista.eos.eos_facts:
        gather_subset: min
        gather_network_resources: interfaces
```
Any `gather_network_resources` that includes `acl_interfaces` will trigger this.

##### EXPECTED RESULTS

I expect the facts to be captured and the task to complete.  It works with `ansible.legacy.eos_facts` just fine.

##### ACTUAL RESULTS

```paste below
TASK [eos facts] ***************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [test-switch-01]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/test-user/.ansible/tmp/ansible-local-277839w07ikcy/ansible-tmp-1611184623.2708738-27848-170346474512606/AnsiballZ_eos_facts.py", line 102, in <module>
        _ansiballz_main()
      File "/home/test-user/.ansible/tmp/ansible-local-277839w07ikcy/ansible-tmp-1611184623.2708738-27848-170346474512606/AnsiballZ_eos_facts.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/test-user/.ansible/tmp/ansible-local-277839w07ikcy/ansible-tmp-1611184623.2708738-27848-170346474512606/AnsiballZ_eos_facts.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_facts', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_arista.eos.eos_facts_payload_5e_kt42t/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_facts.py", line 207, in <module>
      File "/tmp/ansible_arista.eos.eos_facts_payload_5e_kt42t/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_facts.py", line 198, in main
      File "/tmp/ansible_arista.eos.eos_facts_payload_5e_kt42t/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/facts.py", line 109, in get_facts
      File "/tmp/ansible_arista.eos.eos_facts_payload_5e_kt42t/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_arista.eos.eos_facts_payload_5e_kt42t/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acl_interfaces/acl_interfaces.py", line 75, in populate_facts
      File "/tmp/ansible_arista.eos.eos_facts_payload_5e_kt42t/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acl_interfaces/acl_interfaces.py", line 127, in render_config
    IndexError: list index out of range
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

##### WORKAROUNDS

If I collect all but acl_interfaces, it works:
```yaml
    - name: eos facts
      arista.eos.eos_facts:
        gather_subset: min
        gather_network_resources: "!acl_interfaces"
```

Thus this confirms the issue seems to be with the `acl_interfaces` function of the `eos_facts` module.

**Comment by GomathiselviS** [comment]
@ryanmerolle Thanks for submitting the issue. #163 should fix this. Please check and provide your feedback.

**Comment by ryanmerolle** [comment]
I will test, I am just not sure how to build this from the PR.  I just install using a requirements.yml from galaxy.  I will google fu it ang get back you.

**Comment by ryanmerolle** [comment]
I tested the fix, and this resolved the issue.
