### ISSUE TITLE
Facts module produces traceback on devices configured with "vlan internal order" command

### ISSUE THREAD

**Issue by mitchell-foxworth** [ansible-collections/arista.eos#191]
##### SUMMARY
When the arista.eos.eos_facts module is configured to gather VLANs under gather_network_resources, and the end-device is configured with the command "vlan internal order <ascending|descending> <start> <end>" the facts module task will error out with a traceback:
      File "/tmp/ansible_arista.eos.eos_facts_payload_xdofof_m/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 118, in vlan_to_list
    ValueError: invalid literal for int() with base 10: 'internal order ascending range 3950 4000'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

The file referenced (https://github.com/ansible-collections/arista.eos/blob/main/plugins/module_utils/network/eos/facts/vlans/vlans.py) does not make provisions for anything other than a VLAN which might be returned by the device in response to a "show running-config | section ^vlan"

Validated on several models of Arista switches, running EOS 4.23.5M.

The issue can be fixed by inserting these 2 lines between lines 116 & 117:
        elif "internal order" in vlan:
            continue

***However*** there may be other lines of configuration potentially returned by "show running-config | section ^vlan" so a final fix should account for any of those other cases.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugin at:
arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py

lines 111-120

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = None
  configured module search path = ['/users/bigslacker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Oct 26 2020, 20:37:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.5)]
```

##### CONFIGURATION

```
DEFAULT_STDOUT_CALLBACK(/users/bigslacker/netbox-ingestion/ansible.cfg) = yaml
HOST_KEY_CHECKING(/users/bigslacker/netbox-ingestion/ansible.cfg) = False
INTERPRETER_PYTHON(/users/bigslacker/netbox-ingestion/ansible.cfg) = python
PERSISTENT_COMMAND_TIMEOUT(/users/bigslacker/netbox-ingestion/ansible.cfg) = 480
```

##### OS / ENVIRONMENT

Arista EOS 4.23.5M

##### STEPS TO REPRODUCE

Configure an Arista switch with the command "internal order ascending range 3950 4000"
Run a playbook task which gathers vlans (see below)

```
---
- name: Scrape facts from data center switches and populate them into NetBox.
  hosts: [switches]
  gather_facts: no
  connection: local
  vars_files:
    - vars/netbox_ingestion_vars.yml

  tasks:

    - name: Gather facts (Arista)
      arista.eos.eos_facts:
        gather_network_resources:
          - vlans
        gather_subset:
          - hardware
          - interfaces
      when: ansible_network_os == 'arista.eos.eos'
      connection: network_cli

    - meta: end_play
```

##### EXPECTED RESULTS

The task should ignore the "vlan internal order" command and any other global config which is returned by "show running-config | section ^vlan" and only populate the list of vlans.

##### ACTUAL RESULTS

```
$ ansible-playbook aristatest.yml -i inventory/hosts-us_ofs_workers-dev.yml -vvv
ansible-playbook 2.10.6
  config file = /users/bigslacker/netbox-ingestion/ansible.cfg
  configured module search path = ['/users/bigslacker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /users/bigslacker/netbox-ingestion/venv/lib/python3.8/site-packages/ansible
  executable location = /users/bigslacker/netbox-ingestion/venv/bin/ansible-playbook
  python version = 3.8.6 (default, Oct 26 2020, 20:37:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.5)]
Using /users/bigslacker/netbox-ingestion/ansible.cfg as config file
host_list declined parsing /users/bigslacker/netbox-ingestion/inventory/hosts-us_ofs_workers-dev.yml as it did not pass its verify_file() method
script declined parsing /users/bigslacker/netbox-ingestion/inventory/hosts-us_ofs_workers-dev.yml as it did not pass its verify_file() method
Parsed /users/bigslacker/netbox-ingestion/inventory/hosts-us_ofs_workers-dev.yml inventory source with yaml plugin
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
Read vars_file 'vars/netbox_ingestion_vars.yml'
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: aristatest.yml ***************************************************************************************************************************
1 plays in aristatest.yml
Read vars_file 'vars/netbox_ingestion_vars.yml'
Read vars_file 'vars/netbox_ingestion_vars.yml'
Read vars_file 'vars/netbox_ingestion_vars.yml'

PLAY [Scrape facts from data center switches and populate them into NetBox.] ***********************************************************************
Read vars_file 'vars/netbox_ingestion_vars.yml'
META: ran handlers
Read vars_file 'vars/netbox_ingestion_vars.yml'
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos

TASK [Gather facts (Arista)] ***********************************************************************************************************************
task path: /users/bigslacker/netbox-ingestion/aristatest.yml:11
Read vars_file 'vars/netbox_ingestion_vars.yml'
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
skipping: [LAB1AKA149481D] => changed=false 
  skip_reason: Conditional result was False
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
<10.10.255.28> ESTABLISH LOCAL CONNECTION FOR USER: bigslacker
<10.10.255.28> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36 `"&& mkdir "` echo /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531 `" && echo ansible-tmp-1617200929.2929003-22988-35313461490531="` echo /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531 `" ) && sleep 0'
Using module file /users/bigslacker/.ansible/collections/ansible_collections/arista/eos/plugins/modules/eos_facts.py
<10.10.255.28> PUT /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/tmpa7sv24m3 TO /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py
<10.10.255.28> EXEC /bin/sh -c 'chmod u+x /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/ /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py && sleep 0'
<10.10.255.28> EXEC /bin/sh -c 'python /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py && sleep 0'
<10.10.255.28> EXEC /bin/sh -c 'rm -f -r /users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_facts.py", line 207, in <module>
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_facts.py", line 198, in main
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/facts.py", line 118, in get_facts
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 69, in populate_facts
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 99, in render_config
  File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 118, in vlan_to_list
ValueError: invalid literal for int() with base 10: 'internal order ascending range 3950 4000'
fatal: [LAB3VXRTRA01A]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py", line 102, in <module>
        _ansiballz_main()
      File "/users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/users/bigslacker/.ansible/tmp/ansible-local-22972uql_wg36/ansible-tmp-1617200929.2929003-22988-35313461490531/AnsiballZ_eos_facts.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_facts', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_facts.py", line 207, in <module>
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_facts.py", line 198, in main
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/facts.py", line 118, in get_facts
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 69, in populate_facts
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 99, in render_config
      File "/tmp/ansible_arista.eos.eos_facts_payload_7shfue3n/ansible_arista.eos.eos_facts_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/vlans/vlans.py", line 118, in vlan_to_list
    ValueError: invalid literal for int() with base 10: 'internal order ascending range 3950 4000'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
Read vars_file 'vars/netbox_ingestion_vars.yml'
Read vars_file 'vars/netbox_ingestion_vars.yml'
META: ending play

PLAY RECAP *****************************************************************************************************************************************
LAB1AKA149481D             : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
LAB3VXRTRA01A            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by mitchell-foxworth** [comment]
It would probably be more future-proof to replace lines 111-120 with this:

def vlan_to_list(vlan_str):
    vlans = []
    for vlan in vlan_str.split(","):
        if "-" in vlan:
            start, stop = vlan.split("-")
            vlans.extend(range(int(start), int(stop) + 1))
        else:
            try:
                vlans.append(int(vlan))
            except ValueError:
                pass

    return vlans

**Comment by gundalow** [comment]
@mitchell-foxworth Potential fix in https://github.com/ansible-collections/arista.eos/pull/192
