### ISSUE TITLE
Loosing Authentication in 2nd Task

### ISSUE THREAD

**Issue by k-304** [ansible-collections/arista.eos#292]
##### SUMMARY
I use Ansible 2.11 to connect to an Arista Switch (7050) eOS v 1.18.1 using the eAPI.
I used the notes at [this page](https://docs.ansible.com/ansible/latest/network/user_guide/platform_eos.html#example-eapi-group-vars-eos-yml) to define connection Vars.

I wrote a playbook with 2 simple tasks:
```
- name: Gather facts from Arista Switch
  arista.eos.eos_facts:
- arista.eos.eos_banner:
    banner: login
    text: sometext
```
The "Gather Facts" command completes successfully, but the Banner (or any other module used) fails with an "401 Unauthorized".
Whenever I add a 2nd or 3rd Task, it seems like it is no longer authenticated. If I Switch banner / get facts, the banner works, the get Facts doesn't anymore.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
arista.eos
arista.eos.eos_facts
arista.eos.eos_banner

##### ANSIBLE VERSION
```
ansible [core 2.11.3]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.pyenv/versions/3.9.1/envs/ansible2.11/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.pyenv/versions/ansible2.11/bin/ansible
  python version = 3.9.1 (default, Aug 11 2021, 13:21:50) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
Collection Version
---------- -------
arista.eos 3.1.0
```

##### CONFIGURATION
```
# empty
```

##### OS / ENVIRONMENT
Ansible Host: Debian 10 with PyEnv
Target: Arista 7050S-64 (eOS 1.18.1.1F)

##### STEPS TO REPRODUCE
Gonna add some more Playbook data in here:
Group_Var/connection.yml
```
# Connection details to eAPI
ansible_connection: ansible.netcommon.httpapi
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_network_os: arista.eos.eos
ansible_user: apiadmin
ansible_password: !vault |
ansible_become: yes
ansible_become_method: enable
ansible_python_interpreter: /home/user/.pyenv/versions/3.9.1/envs/ansible2.11/bin/python3.9
ANSIBLE_EOS_USE_SESSIONS: 1
```

The Playbook:
```
---
- name: Gather facts from Arista Switch
  arista.eos.eos_facts:
- arista.eos.eos_banner:
    banner: login
    text: testtext
```

##### ACTUAL RESULTS
```
ansible-playbook [core 2.11.3] 
  config file = None
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/USER/.pyenv/versions/3.9.1/envs/ansible2.11/lib/python3.9/site-packages/ansible
  ansible collection location = /home/USER/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/USER/.pyenv/versions/ansible2.11/bin/ansible-playbook
  python version = 3.9.1 (default, Aug 11 2021, 13:21:50) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/inventory/switches-prod/legacy-group_mappings as it did not pass its verify_file() method
auto declined parsing /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/inventory/switches-prod/legacy-group_mappings as it did not pass its verify_file() method
Parsed /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/inventory/switches-prod/platform_mapping inventory source with ini plugin
Loading collection arista.eos from /home/USER/.ansible/collections/ansible_collections/arista/eos
statically imported: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/eos/main.yml
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
redirecting (type: action) arista.eos.eos_banner to arista.eos.eos
statically imported: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/eos/dummy.yml
redirecting (type: action) arista.eos.eos_command to arista.eos.eos
statically imported: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/eos/upgrade.yml
redirecting (type: action) arista.eos.eos_command to arista.eos.eos
redirecting (type: modules) ansible.builtin.eos_command to arista.eos.eos_command
redirecting (type: modules) ansible.builtin.eos_command to arista.eos.eos_command
redirecting (type: modules) ansible.builtin.eos_command to arista.eos.eos_command
statically imported: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/ios/main.yml
Loading collection cisco.ios from /home/USER/.ansible/collections/ansible_collections/cisco/ios
redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
statically imported: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/ios/dummy.yml
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
Loading callback plugin default of type stdout, v2.0 from /home/USER/.pyenv/versions/3.9.1/envs/ansible2.11/lib/python3.9/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yml *********************************************************
Positional arguments: playbook.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/inventory/switches-prod',)
subset: zhloccs11a
vault_password_files: ('/home/USER/vault_prod.yml',)
forks: 5
1 plays in playbook.yml

PLAY [all] *********************************************************************
META: ran handlers
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
Loading collection ansible.netcommon from /home/USER/.ansible/collections/ansible_collections/ansible/netcommon

TASK [switch-stats : Gather facts from Arista Switch] **************************
task path: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/eos/main.yml:3
Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<10.168.41.11> attempting to start connection
<10.168.41.11> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /home/USER/.pyenv/versions/ansible2.11/bin/ansible-connection
<10.168.41.11> local domain socket does not exist, starting it
<10.168.41.11> control socket path is /home/USER/.ansible/pc/ef0a1dea04
<10.168.41.11> Loading collection ansible.netcommon from /home/USER/.ansible/collections/ansible_collections/ansible/netcommon
<10.168.41.11> Loading collection arista.eos from /home/USER/.ansible/collections/ansible_collections/arista/eos
<10.168.41.11> Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
<10.168.41.11> local domain socket listeners started successfully
<10.168.41.11> loaded API plugin ansible_collections.arista.eos.plugins.httpapi.eos from path /home/USER/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py for network_os arista.eos.eos
<10.168.41.11> 
<10.168.41.11> local domain socket path is /home/USER/.ansible/pc/ef0a1dea04
Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
<10.168.41.11> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<10.168.41.11> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<10.168.41.11> ESTABLISH LOCAL CONNECTION FOR USER: kjo
<10.168.41.11> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i `"&& mkdir "` echo /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173 `" && echo ansible-tmp-1636465038.4020698-11673-171872335703173="` echo /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173 `" ) && sleep 0'
Using module file /home/USER/.ansible/collections/ansible_collections/arista/eos/plugins/modules/eos_facts.py
<10.168.41.11> PUT /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/tmpdikam5ml TO /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173/AnsiballZ_eos_facts.py
<10.168.41.11> EXEC /bin/sh -c 'chmod u+x /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173/ /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173/AnsiballZ_eos_facts.py && sleep 0'
<10.168.41.11> EXEC /bin/sh -c '/home/USER/.pyenv/versions/3.9.1/envs/ansible2.11/bin/python3.9 /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173/AnsiballZ_eos_facts.py && sleep 0'
<10.168.41.11> EXEC /bin/sh -c 'rm -f -r /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465038.4020698-11673-171872335703173/ > /dev/null 2>&1 && sleep 0'
ok: [zhloccs11a] => {
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [
            "10.168.41.11"
        ],
        "ansible_net_all_ipv6_addresses": [],
        "ansible_net_api": "eapi",
        "ansible_net_filesystems": [
            "file:",
            "flash:",
            "system:"
        ],
        "ansible_net_fqdn": "zhloccs11a",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "interfaces",
            "default",
            "hardware"
        ],
        "ansible_net_hostname": "zhloccs11a",
        "ansible_net_interfaces": {
            "Ethernet1": {
                "bandwidth": 10000000000,
                "description": "",
                "duplex": "duplexFull",
                "ipv4": {},
                "lineprotocol": "notPresent",
                "macaddress": "00:1c:73:ae:d9:82",
                "mtu": 9214,
                "operstatus": "notconnect",
                "type": "bridged"
            },
            <!-- .... -->
            },
            "Ethernet9": {
                "bandwidth": 10000000000,
                "description": "",
                "duplex": "duplexFull",
                "ipv4": {},
                "lineprotocol": "notPresent",
                "macaddress": "00:1c:73:ae:d9:8a",
                "mtu": 9214,
                "operstatus": "notconnect",
                "type": "bridged"
            },
            "Management1": {
                "bandwidth": 1000000000,
                "description": "",
                "duplex": "duplexFull",
                "ipv4": {
                    "address": "10.168.41.11",
                    "masklen": 24
                },
                "lineprotocol": "up",
                "macaddress": "00:1c:73:ae:d9:80",
                "mtu": 1500,
                "operstatus": "connected",
                "type": "routed"
            }
        },
        "ansible_net_memfree_mb": 2309.30078125,
        "ansible_net_memtotal_mb": 3870.77734375,
        "ansible_net_model": "DCS-7050S-64-R",
        "ansible_net_neighbors": {},
        "ansible_net_python_version": "3.9.1",
        "ansible_net_serialnum": "JPE14465742",
        "ansible_net_system": "eos",
        "ansible_net_version": "4.18.1.1F",
        "ansible_network_resources": {}
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": false,
            "gather_network_resources": null,
            "gather_subset": [
                "!config"
            ],
            "provider": null
        }
    }
}
redirecting (type: action) arista.eos.eos_banner to arista.eos.eos

TASK [switch-stats : arista.eos.eos_banner] ************************************
task path: /home/USER/projects/bc/ansible-roles/datacenter-network/switch-update/roles/switch-stats/tasks/eos/main.yml:5
Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<10.168.41.11> attempting to start connection
<10.168.41.11> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /home/USER/.pyenv/versions/ansible2.11/bin/ansible-connection
<10.168.41.11> found existing local domain socket, using it!
<10.168.41.11> ESTABLISH HTTP(S) CONNECTFOR USER: apiadmin TO https://10.168.41.11:443
<10.168.41.11> firing event: on_become
<10.168.41.11> firing event: on_become
<10.168.41.11> firing event: on_become
<10.168.41.11> firing event: on_become
<10.168.41.11> firing event: on_become
<10.168.41.11> firing event: on_become
<10.168.41.11> updating play_context for connection
<10.168.41.11> 
<10.168.41.11> local domain socket path is /home/USER/.ansible/pc/ef0a1dea04
Trying secret FileVaultSecret(filename='/home/USER/vault_prod.yml') for vault_id=default
redirecting (type: action) arista.eos.eos_banner to arista.eos.eos
redirecting (type: action) arista.eos.eos_banner to arista.eos.eos
<10.168.41.11> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<10.168.41.11> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<10.168.41.11> ESTABLISH LOCAL CONNECTION FOR USER: kjo
<10.168.41.11> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i `"&& mkdir "` echo /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313 `" && echo ansible-tmp-1636465042.0958014-11701-220074699067313="` echo /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313 `" ) && sleep 0'
Using module file /home/USER/.ansible/collections/ansible_collections/arista/eos/plugins/modules/eos_banner.py
<10.168.41.11> PUT /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/tmpl5ujjw41 TO /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py
<10.168.41.11> EXEC /bin/sh -c 'chmod u+x /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/ /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py && sleep 0'
<10.168.41.11> EXEC /bin/sh -c '/home/USER/.pyenv/versions/3.9.1/envs/ansible2.11/bin/python3.9 /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py && sleep 0'
<10.168.41.11> EXEC /bin/sh -c 'rm -f -r /home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py", line 100, in <module>
    _ansiballz_main()
  File "/home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_banner', init_globals=dict(_module_fqn='ansible_collections.arista.eos.plugins.modules.eos_banner', _modlib_path=modlib_path),
  File "/home/USER/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/USER/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/USER/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_banner.py", line 218, in <module>
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_banner.py", line 201, in main
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_banner.py", line 144, in map_config_to_obj
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py", line 711, in run_commands
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py", line 533, in run_commands
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py", line 500, in run_queue
  File "/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
ansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized
fatal: [zhloccs11a]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/USER/.ansible/tmp/ansible-local-11613sndi2x0i/ansible-tmp-1636465042.0958014-11701-220074699067313/AnsiballZ_eos_banner.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_banner', init_globals=dict(_module_fqn='ansible_collections.arista.eos.plugins.modules.eos_banner', _modlib_path=modlib_path),\n  File \"/home/USER/.pyenv/versions/3.9.1/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/home/USER/.pyenv/versions/3.9.1/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/home/USER/.pyenv/versions/3.9.1/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_banner.py\", line 218, in <module>\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_banner.py\", line 201, in main\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_banner.py\", line 144, in map_config_to_obj\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py\", line 711, in run_commands\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py\", line 533, in run_commands\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/eos.py\", line 500, in run_queue\n  File \"/tmp/ansible_arista.eos.eos_banner_payload_mw7k6hen/ansible_arista.eos.eos_banner_payload.zip/ansible/module_utils/connection.py\", line 195, in __rpc__\nansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
zhloccs11a                 : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```

**Comment by GomathiselviS** [comment]
@k-304  I am unable to reproduce this issue with the configs you provided.

```
[eos]
x.x.x.x

[eos:vars]
ansible_network_os=arista.eos.eos
ansible_user=ansible
ansible_ssh_pass=ansible
ansible_become=true
ansible_become_method=enable
ansible_become_pass=admin
ansible_connection=ansible.netcommon.httpapi
ansible_password: !vault |
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ANSIBLE_EOS_USE_SESSIONS: 1

[all:vars]
ansible_python_interpreter=python
```

```
---
- hosts: eos
  gather_facts: false
  tasks:
  - name: Gather facts from Arista Switch
    arista.eos.eos_facts:
  - arista.eos.eos_banner:
      banner: login
      text: sometext
```

```
ansible [core 2.11.0b4]  (ans-2.11 ae90774f2b) last updated 2021/04/06 21:49:40 (GMT -400)
  config file = /home/gosriniv/github/ansible.cfg
  configured module search path = ['/home/gosriniv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gosriniv/Project/ansible/lib/ansible
  ansible collection location = /home/gosriniv/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gosriniv/.pyenv/versions/ansible-3.8.0-pyenv-venv/bin/ansible
  python version = 3.8.0 (default, Oct 15 2021, 11:50:09) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.0.2
  libyaml = True
```

**Comment by gmuloc** [comment]
Could be related to this: https://github.com/ansible/ansible/issues/75503
