### ISSUE TITLE
eos_config - unable push second time with configuration existed!

### ISSUE THREAD

**Issue by mmihir82** [ansible-collections/arista.eos#372]
##### SUMMARY
Unable to push configuration second time without any changes using eos_config module
What I meant here the following:
- Arista SW ZTP with base configuration and with MGMT IP Address 
- Step2: Push via Ansible 
  - host_vars: two files: interfaces.yml and bgp.yml 
  - render the vars with given jinja2 template and push to Arista SW via network_cli 
- Without any interfaces and BGP configuration on the SW, the push is Successful.
- Running second time with updated BGP vars and throw errors, 
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Invalid input (at token 0: 'router-id')
fatal: [eos_hostname1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_eos_config_payload_bxj_oa7j/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py", line 518, in <module>
      File "/tmp/ansible_eos_config_payload_bxj_oa7j/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py", line 440, in main
      File "/tmp/ansible_eos_config_payload_bxj_oa7j/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py", line 643, in load_config
      File "/tmp/ansible_eos_config_payload_bxj_oa7j/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py", line 533, in load_config
      File "/tmp/ansible_eos_config_payload_bxj_oa7j/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py", line 567, in edit_config
      File "/tmp/ansible_eos_config_payload_bxj_oa7j/ansible_eos_config_payload.zip/ansible/module_utils/connection.py", line 190, in __rpc__
    ansible.module_utils.connection.ConnectionError: Invalid input (at token 0: 'router-id')
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
reason of the above error, is because the configuration is already existed on the SW.
##### ANSIBLE VERSION
```
ansible 2.9.27
  config file = /opt/netauto/ansible.cfg
  configured module search path = ['/opt/netauto/library']
  ansible python module location = ~/.ENV/netauto/lib/python3.6/site-packages/ansible
  executable location = ~/.ENV/netauto/bin/ansible
  python version = 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]
```

##### COLLECTION VERSION
```
ansible-galaxy collection install arista.eos 
lastest: 5.0.1 
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/opt/netauto/ansible.cfg) = True
COMMAND_WARNINGS(/opt/netauto/ansible.cfg) = False
DEFAULT_CALLBACK_WHITELIST(/opt/netauto/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/opt/netauto/ansible.cfg) = ['/opt/netauto/filter_plugins']
DEFAULT_FORCE_HANDLERS(/opt/netauto/ansible.cfg) = True
DEFAULT_FORKS(/opt/netauto/ansible.cfg) = 50
DEFAULT_HASH_BEHAVIOUR(/opt/netauto/ansible.cfg) = merge
DEFAULT_HOST_LIST(/opt/netauto/ansible.cfg) = ['/opt/netauto/inventories/hosts']
DEFAULT_JINJA2_EXTENSIONS(/opt/netauto/ansible.cfg) = jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n
DEFAULT_MANAGED_STR(/opt/netauto/ansible.cfg) = ### Ansible Managed File
DEFAULT_MODULE_PATH(/opt/netauto/ansible.cfg) = ['/opt/netauto/library']
DEFAULT_ROLES_PATH(/opt/netauto/ansible.cfg) = ['/opt/netauto/roles']
DEFAULT_STDOUT_CALLBACK(/opt/netauto/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/ngcjetson/.vault_pass
DEPRECATION_WARNINGS(/opt/netauto/ansible.cfg) = False
HOST_KEY_CHECKING(/opt/netauto/ansible.cfg) = False
INTERPRETER_PYTHON(/opt/netauto/ansible.cfg) = /usr/bin/python3.6
RETRY_FILES_ENABLED(/opt/netauto/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu: 18.04 

##### STEPS TO REPRODUCE

```
role: arista_routing / tasks/bgp.yml
---
- name: "BGP - PUSH"
  eos_config:
    provider: "{{ arista_credentials }}"
    src: "bgp.j2"
    save_when: changed

vars:
router_bgp:
  bgp_asn: 100
  bgp_router_id: 192.168.1.1

  bgp_defaults:
    - bgp asn notation asdot
    - bgp default ipv4-unicast transport ipv6
    - maximum-paths 128 ecmp 128
    - bgp additional-paths install
    - bgp log-neighbor-changes
    - distance bgp 20 200 200

```

**Comment by mmihir82** [comment]
i was able to figure the issue, i believe it due to ansible version and eos collection.
